//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mariusz_Stefan {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mariusz_Stefan.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Agunie, Ajgunie, Akunie, alraunie, Alunie, ałunie, Aromunie, awifaunie, babunie, bakunie, bazunie, biegunie, bielunie, biosaunie, bizunie, Bohunie, bordunie, Braunie, Brunie, bryzgunie, bunie, buziunie, cabiunie, całunie, Changchunie, ciotunie, ciwunie, Coropunie, córunie, cywunie, Czangczunie, ćpunie, Datsunie, diunie, dosunie, Dragunie, dwubiegunie, dyspareunie, dyzunie, dziadunie, dziadziunie, dziunie, Elżunie, entomofaunie, epifaunie, Ewunie, Faunie, Fortunie, frunie, Fushunie, Fuszunie, Futunie, gunie, [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string accounie {
            get {
                return ResourceManager.GetString("accounie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aasen, abdomen, Aberdeen, aborygen, Aborygen, acenaften, acetylen, Aden, aglutynogen, Ahonen, akwen, Alen, alergen, alfametylonaftalen, alken, Allen, alloantygen, aloesen, amen, amfisben, aminobenzen, aminotoluen, Amundsen, amylen, anaben, anafilaktogen, ancien, Andersen, androgen, anekumen, Anfinsen, anten, antracen, antyandrogen, antyestrogen, antygen, antypiren, aptekarzówien, arden, Arden, aren, arierscen, arsen, Arsen, asfalten, Aten, aulakogen, Austen, autoocen, awanscen, awen, azobenzen, azotogen, az [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string aiden {
            get {
                return ResourceManager.GetString("aiden", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu abort, aeroport, akwafort, Allport, antyimport, antyport, antysport, aort, aport, asport, awanport, bakbort, Beaufort, bort, botfort, Chamfort, consort, cyklosport, czort, Davenport, dekort, deport, descort, dyskomfort, egzort, eksport, escort, eskort, Eurosport, fluorofort, fort, Fort, gazoport, heliport, hydrotransport, import, kohort, komfort, kort, kurort, mikroport, minikort, miniraport, motosport, Naftoport, Newport, ort, oxycort, passport, paszport, pomort, port, Port, półkomfort, półkort, przedport, [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string behemort {
            get {
                return ResourceManager.GetString("behemort", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu tak, nie, nie wiem, być może, na pewno, to mało prawdopodobne, nie sądzę, jeszcze się pytasz?, tak (żartuję hehe), hehe)))))))))))))))))), tak, nie, tak (no homo), zaiste, no chyba cię pambuk opuścił, raczej nie, jeszcze nie, teraz już tak, może kiedyś, tak jest panie kapitanie, panie januszu NIE, jeszcze nie wiem, daj mi chwilę to się zastanowię, nie wiem zarobiony jestem przyjdź Pan jutro, a czy papież sra w lesie?, co za debil wymyśla te pytania, jak najbardziej, gówno prawda, jeszcze jak, jest możliwe.
        /// </summary>
        internal static string czy {
            get {
                return ResourceManager.GetString("czy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu absurdziku, abuliku, Achteliku, achterpiku, Adamiku, adiutanciku, adoniku, adresiku, adwokaciku, aerobiku, aerodynamiku, afterpiku, agenciku, agrochemiku, agrolotniku, agrotechniku, akademiku, akapiciku, akatoliku, akcenciku, akciku, akcydensiku, akcyźniku, akordeoniku, akordziku, Alberciku, albumiku, alchemiku, alembiku, alergiku, algebraiku, alkoholiku, almiku, alniku, altanniku, Amalriku, amanciku, Ambroziku, amorfiku, anaboliku, ananasiku, andruciku, anemiku, Angliku, angliku, anglokatoliku, Antoniku, A [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string deffiku {
            get {
                return ResourceManager.GetString("deffiku", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The file could not be read:.
        /// </summary>
        internal static string file_cannot_be_read {
            get {
                return ResourceManager.GetString("file_cannot_be_read", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu pod mostem, w dupie, na głowie, na kompie, w parafii, w koszu, w fapfolderze, na rowerze.
        /// </summary>
        internal static string gdzie_prefix {
            get {
                return ResourceManager.GetString("gdzie_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turambara,
        ///yojca,
        ///Lorda Nargogha,
        ///Rankina,
        ///Kathai,
        ///Behemorta,
        ///orgieła,
        ///Stillborna,
        ///Metalusa,
        ///kicka,
        ///podbiela,
        ///Sedinusa,
        ///Hakkena,
        ///Tebega,
        ///Sermacieja,
        ///t3trisa,
        ///optiego,
        ///Hrabuli,
        ///FaceDancera,
        ///Holiego.Deatha,
        ///Ramzesa,
        ///POLIPa,
        ///mateusza(stefana),
        ///Xysia,
        ///Germanotty,
        ///Berlina,
        ///8azyliszka,
        ///Seekera,
        ///Murezora,
        ///RIPa,
        ///Aidena,
        ///Accouna,
        ///Fela,
        ///Dracii,
        ///Niziołki,
        ///Mavericka,
        ///P_aula,
        ///Brylanta,
        ///deffika,
        ///Deviusa,
        ///Gofra,
        ///JamesaVooa,
        ///Black Shadowa,
        ///emqiego,
        ///nerv4,
        ///Pałkera,
        ///Princess Nua, [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string gdzie_suffix {
            get {
                return ResourceManager.GetString("gdzie_suffix", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Achai, Adonai, AI, Araguai, assai, bai, banzai, bonsai, bonzai, bulai, Cambrai, Chennai, cygai, Czai, czai, displai, Douai, Enlai, fai, faradai, gai, Gai, grai, gronostai, gudłai, hai, haikai, Hawai, heliai, Himalai, hultai, Hyundai, hyundai, jambalai, Jamiroquai, jamrai, kacabai, Kai, Kasai, kawaii, kawai, kuczbai, kwilai, lai, laogai, liszai, lokai, mai, Mai, Mamai, mazai, mazgai, narai, Nauzykai, Nicolai, nieurodzai, njai, obczai, odzwyczai, okrai, paciai, pagai, pai, papai, Piai, Prai, pralai, przehulta [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string kathai {
            get {
                return ResourceManager.GetString("kathai", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu akademicku, alchemicku, annamicku, antybolszewicku, antyjezuicku, antykatolicku, antysemicku, azjanicku, babicku, baćkowicku, baranowicku, bartnicku, barwicku, bielicku, bierzwnicku, biskupicku, błędowicku, bobolicku, bobrowicku, bobrownicku, boleszkowicku, bolszewicku, borkowicku, botnicku, brodnicku, bronowicku, brunszwicku, brzeźnicku, Buicku, bytnicku, cenobicku, cewicku, Chadwicku, chamicku, charsznicku, Chicku, chłopicku, chmielnicku, chojnicku, chrząstowicku, chwałowicku, cieplicku, ciężkowicku, Cric [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string kicku {
            get {
                return ResourceManager.GetString("kicku", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turambarem, yojecem, Lordem Nargoghiem, Rankinem, Kathajcem, Behemortem, orgiełem, Stillbornem, Metalusem, kickiem, podbielem, Sedinusem, Hakkenem, Tebem, Sermaciejem, t3trisem, optim, Hrabulą, FaceDancerem, Holim.Death, Ramzesem, POLIPem, mateuszem(stefanem), Xysiem, Germanottą, Berlinem, 8azyliszkiem, Seekerem, Murezorem, RIPem, Aidenem, Accounem, Felem, Dracią, Niziołką, Maverickiem, P_aulem, Brylantem, deffikiem, Deviusem, Gofrem, JamesemVooem, Black Shadowem, emqim, nerv3m, Pałkerem, Princess Nuem, Rys [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string kim {
            get {
                return ResourceManager.GetString("kim", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turambara, yojca, Lorda Nargogha, Rankina, Kathajca, Behemorta, orgieła, Stillborna, Metalusa, kicka, podbiela, Sedinusa, Hakkena, Teba, Sermacieja, t3trisa, optiego, FaceDancera, Holiego.Deatha, Ramzesa, POLIPa, mateusza(stefana), Xysia, Germanotty, Berlina, 8azyliszka, Seekera, Murezora, RIPa, Aidena,  Accouna, Fela, Dracii, Niziołki, Mavericka, P_aula, Brylanta, deffika, Deviusa, Gofra, JamesaVooa, Black Shadowa, emqiego, nerv4, Pałkera, Princess Nua, Rysi, Shakera, Artiusa, Stefana, Xerbera, Elana, Vodę [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string kogo {
            get {
                return ResourceManager.GetString("kogo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turambarowi, yojecowi, Lordowi Nargoghowi, Rankinowi, Kathajcowi, Behemortowi, orgiełowi, Stillbornowi, Metalusowi, kickowi, podbielowi, Sedinusowi, Hakkenowi, Tebowi, Sermaciejowi, t3trisowi, optiemi, Hrabuli, FaceDancerowi, Holy.Deathowi, Ramzesowi, POLIPowi, mateuszowi(stefanowi), Xysiowi, Germanotcie, Berlinowi, 8azyliszkowi, Seekerowi, Murezorowi, RIPowi, Aidenowi, Accounowi, Felowi, Dracii, Niziołce, Maverickowi, P_aulowi, Brylantowi, deffikowi, Deviusowi, Gofrowi, JamesVoooooowi, Black Shadowowowowi, [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string komu {
            get {
                return ResourceManager.GetString("komu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turambar, yojec, Lord Nargogh, Rankin, Kathajec, Behemort, orgiełe, Stillborn, Metalus, kicek, podbiel, Sedinus, Hakken, Teb, Sermaciej, t3tris, opti, Hrabula, FaceDancer, Holy.Death, Ramzes, POLIP, mateusz(stefan), Xysiu, Germanotta, Berlin, 8azyliszek, Seeker, Murezor, RIP, Aiden, Accoun, Fel, Dracia, Niziołka, Maverick, P_aul, Brylant, deffik, Devius, Gofer, JamesVoo, Black Shadow, emqi, nerv0, Pałker, Princess Nue, Rysia, Shaker, Artius, Xerber, Elano, Voda, Xardas, Abyss, Bethezer, Knight Martius, Mysq [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string kto {
            get {
                return ResourceManager.GetString("kto", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Acoście, antyroście, Arioście, awanpoście, Babimoście, boście, brzoście, chłodnoroście, chłoście, chrząstkozroście, chwoście, ciepłoroście, coście, Coście, diagnoście, Dobrogoście, donoście, doproście, eksstaroście, farmakognoście, Froście, głoście, goście, gronoroście, hoście, ichmoście, impoście, jegomoście, jejmoście, Jooście, kłoście, kokoście, kompoście, kontrapoście, koście, kościozroście, krasnoroście, kroście, Lubogoście, łomikoście, miętoście, Miłogoście, miniwzroście, Mladoście, monopoście, moście [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string lghoscie {
            get {
                return ResourceManager.GetString("lghoscie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aaronie, Abaddonie, abandonie, Abdonie, abiosestonie, abutilonie, acetofenonie, acetonie, acetyloacetonie, Acheronie, Achesonie, Adamsonie, Adramyttionie, adytonie, aegikranionie, aeolodikonie, aeolodionie, aeolomelodikonie, aeolopantaleonie, aerofonie, aeroplanktonie, aflastonie, afonie, Agamemnonie, agamogonie, agathodaimonie, Agatonie, aglikonie, agonie, agrafonie, aigikranionie, Ajjalonie, akordeonie, Akronie, akroterionie, akrotonie, aksonie, Akteonie, aktynonie, akwawibronie, Akwilonie, alabastronie,  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string lordeonie {
            get {
                return ResourceManager.GetString("lordeonie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu aerologu, afrykanologu, agrobiologu, agroekologu, agrogeologu, agroklimatologu, agrometeorologu, akcentologu, aksjologu, aktynologu, alergologu, algologu, alkohologu, analogu, anatomopatologu, andragogu, andrologu, anestezjologu, angelologu, angiologu, antropologu, antydialogu, antypedagogu, apologu, arachnologu, archeologu, astrobiologu, astrologu, asyriologu, audiologu, bakteriologu, balneologu, baltologu, bałtologu, barłogu, batogu, bibliologu, biocenologu, bioekologu, bioklimatologu, biologu, biometeoro [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string nargoghu {
            get {
                return ResourceManager.GetString("nargoghu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Aalborgu, Adalbergu, angiochirurgu, Augsburgu, Bambergu, Bergu, Blacksburgu, Bloombergu, borgu, Brandenburgu, Carlsbergu, Cherbourgu, chirurgu, Coburgu, Cronenbergu, lewaku i cyborgu, demiurgu, dramaturgu, Duisburgu, Edynburgu, Ehrenbergu, embargu, Engelbergu, Erenburgu, ergu, Felbergu, Fitelbergu, Flensburgu, Freibergu, Fryburgu, ftyzjochirurgu, Fyrstenbergu, Georgu, Gettysburgu, Ginsbergu, Goldbergu, gorgu, Grynbergu, Gutenbergu, Habsburgu, Hamburgu, Heidelbergu, Heisenbergu, Hindenburgu, Homburgu, iceber [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string orgu {
            get {
                return ResourceManager.GetString("orgu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu sam jesteś pedałem, sam jesteś gejem, lubię homosiów, chodź przytul mnie, jak ty do mnie mówisz, lubię gdy mnie tak nazywasz, przytul mnie ze swych ramion zbuduj schron, będziesz gwałcony przez 5 dni bo napisałeś do potężnego geja.
        /// </summary>
        internal static string pedal {
            get {
                return ResourceManager.GetString("pedal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Amielu, Anielu, arcydzięgielu, arielu, barcielu, bielu, budzicielu, Bukielu, burzycielu, chmielu, chruścielu, Chruścielu, chrzcicielu, ciemiężycielu, czcicielu, Czepielu, czyścicielu, danielu, Dogielu, donosicielu, doręczycielu, dostarczycielu, dręczycielu, Dubielu, dusicielu, Dykielu, dzierżycielu, dzięgielu, Ezechielu, Fugielu, Gabrielu, Gamalielu, glockenspielu, głosicielu, gnębicielu, gorszycielu, grabicielu, Grygielu, grządzielu, Gurbielu, gwałcicielu, Jankielu, Jokielu, judzicielu, Jurgielu, karmiciel [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string podbielu {
            get {
                return ResourceManager.GetString("podbielu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Arequipie, chipie, chlipie, cipie, clipie, dipie, dowcipie, dżipie, ekipie, filipie, halfpipie, hipie, hydropolipie, Josipie, kipie, klipie, langskipie, lipie, mikrochipie, nipie, Nowolipie, Philipie, pipie, pochlipie, rozchlipie, skipie, slipie, ślipie, tripie, wideoklipie, wychlipie, zachlipie, Zalipie, zipie, glucie z nosa.
        /// </summary>
        internal static string polipie {
            get {
                return ResourceManager.GetString("polipie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abderze, Abnerze, aborterze, absorberze, abwerze, adapterze, Adenauerze, Adlerze, adsorberze, aferze, afrykanerze, Ahaswerze, ajerze, akuszerze, alferze, Algierze, alkierze, alkoholomierze, Almayerze, alsiferze, Alzheimerze, Amberze, ambicjonerze, amperomierze, amperowoltomierze, amperze, amplatzerze, amplitunerze, angledozerze, ankieterze, antreprenerze, antybohaterze, antykamerze, antymerze, antyperze, aporterze, aranżerze, archiprezbiterze, archiwizerze, arcypasterze, arkebuzerze, aromatyzerze, artbuyerz [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string seekerze {
            get {
                return ResourceManager.GetString("seekerze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu aldreju, Aleksieju, Andreju, Andrieju, Andrzeju, Anhueju, archijereju, archireju, asindzieju, bakcheju, Bartłomieju, bartodzieju, beglerbeju, bejlerbeju, beju, Betleju, Błażeju, bobsleju, Bokieju, borodzieju, bromoleju, Celeju, choreju, chutneju, chwieju, czarodzieju, czatneju, Dadeju, Dahomeju, Deju, dichoreju, didżeju, displeju, dobrodzieju, Dreju, Durleju, dychoreju, dyskdżokeju, dytrocheju, dzieju, dżerseju, dżokeju, eseju, firleju, Freju, Fudaleju, geju, gleju, greju, hartleju, Hofeju, hokeju, Hopeju,  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string sermacieju {
            get {
                return ResourceManager.GetString("sermacieju", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu around the head, viciously, repeatedly, in the face, to death, in the balls,
        ///in the ass, savagely, brutally, infinitely, deeply, mercilessly, randomly, homosexually,
        ///keenly, accurately, ironically, gayly, outrageously, straight through the heart, immediately, unavoidably,
        ///from the inside, around a bit, from outer space, gently, silently, for real, for no apparent reason, specifically, maybe,
        ///allegedly, once and for all, for life, stealthly, energetically, frightfully, in the groin, in the dignity, in th [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string slap_areas {
            get {
                return ResourceManager.GetString("slap_areas", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu large, huge, small, tiny, enormous, massive, rusty, gay, pink, sharpened, lethal,
        ///poisoned, toxic, incredible, powerful, wonderful, priceless, explosive, rotten, smelly, puny, toy, deadly,
        ///mortal, second-rate, second-hand, otherwise useless, magical, pneumatic, manly, sissy, iron, steel, golden, filthy,
        ///semi-automatic, invisible, infected, spongy, sharp-pointed, undead, horrible, intimidating, murderous, intergalactic, serious,
        ///nuclear, cosmic, mad, insane, rocket-propelled, holy, super, homosexual, ima [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string slap_sizes {
            get {
                return ResourceManager.GetString("slap_sizes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu trout, fork, mouse, bear, piano, cello, vacuum, mosquito, sewing needle, nail,
        ///fingernail, opti, penis, whale, cookie, straight-arm punch, roundhouse kick, training shoe, dynamite stick,
        ///Justin Bieber CD, fart cloud, dildo, lightsaber, rock, stick, nigger, dinosaur, soap, foreskin, sock, underwear,
        ///herring, spider, snake, ming vase, cow, jackhammer, hammer and sickle, razorblade, daemon, trident, gofer, alligator,
        ///bag of piss, lobster, beer pad, toaster, printer, nailgun, banana bomb, fetus, unicorn sta [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string slap_tools {
            get {
                return ResourceManager.GetString("slap_tools", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu slaps, hits, smashes, beats, bashes, smacks, blasts, punches, stabs,
        ///kills, decapitates, crushes, devastates, massacres, assaults, tackles, abuses, slams, slaughters,
        ///obliderates, wipes out, pulverizes, granulates, stuns, knocks out, strikes, bitchslaps, scratches,
        ///pounds, bangs, whacks, rapes, eats, destroys, does nothing to, dooms, evaporates,
        ///does something to, taunts, disrespects, disarms, mauls, dismembers, defuses, butchers, annihilates,
        ///tortures, shatters, wrecks, toasts, dominates, suffocates,  [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string slap_verbs {
            get {
                return ResourceManager.GetString("slap_verbs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu babrane, bazgrane, brane, chamrane, Coltrane, Crane, czochrane, dobierane, dobrane, docierane, dodzierane, dograne, doorane, dopierane, doprane, dożerane, grane, jarane, karane, nabazgrane, nabierane, nabrane, nacierane, nadbierane, naddzierane, nadebrane, nadżerane, naobierane, napaprane, napierane, naponiewierane, naprane, narozdzierane, nasrane, naścierane, nawybierane, nazbierane, niebabrane, niebazgrane, niebrane, niechamrane, nieczochrane, niedobierane, niedobrane, niedocierane, niedodzierane, niedogr [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string srane {
            get {
                return ResourceManager.GetString("srane", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abebie, amebie, Batszebie, chlebie, ciebie, cybebie, dogrzebie, dojebie, efebie, entamebie, Erebie, Euzebie, Febie, glebie, Glebie, Gottliebie, grzebie, Halebie, Hebie, jebie, Kalebie, kolebie, kubebie, Kutrzebie, kwebie, Loebie, Łebie, macebie, Maghrebie, miksamebie, najebie, niebie, odgrzebie, podglebie, podjebie, podniebie, pogrzebie, pojebie, potrzebie, przegrzebie, przejebie, przyjebie, rozgrzebie, rozjebie, rozkolebie, rubebie, siebie, tekamebie, ujebie, webie, wertebie, Wielebie, wjebie, wygrzebie, w [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string tebie {
            get {
                return ResourceManager.GetString("tebie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu autorytet, Bastet, dysparytet, edylitet, epitet, fakultet, immunitet, kastet, komitet, kwartet, kwintet, lutet, majorytet, moralitet, motet, multiwersytet, nobilitet, oktet, parytet, pasztet, podkomitet, priorytet, Radiokomitet, sekstet, septet, stet, unbelastet, uniwersytet, Bernadet, bidet, bzdet, Cadet, cedet, Daudet, det, godet, kadet, kryptotandet, pedet, tandet, wedet, wendet, widet, wudet, naplet, ty chuju.
        /// </summary>
        internal static string tet {
            get {
                return ResourceManager.GetString("tet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Abarisie, Acisie, Adonisie, agatisie, Agisie, Agnisie, aksisie, aldisie, Alexisie, Aloisie, Amadisie, amarylisie, amaryllisie, Amicisie, anastasisie, anateksisie, anglaisie, anolisie, antropornisie, Anubisie, Apisie, aprilisie, Aramisie, ausweisie, autokomisie, autoserwisie, bajkopisie, Barcisie, Baublisie, benefisie, Betisie, bisie, Blaisie, borgisie, Borisie, brudnopisie, Cacoyannisie, calisie, cassisie, cefalaspisie, cellulitisie, Celtisie, Chrisie, Cialisie, cienkopisie, cisie, clematisie, cruisie, czar [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string tetrisie {
            get {
                return ResourceManager.GetString("tetrisie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu abszycie, andaluzycie, andezycie, angielszczycie, anglezycie, anortozycie, baczycie, bajczycie, bajdurzycie, bałuszycie, bazycie, bebeszycie, beczycie, błyszczycie, boczycie, brązycie, broczycie, bronzycie, brzęczycie, brzycie, buczycie, buńczuczycie, burczycie, burłaczycie, burmuszycie, burzycie, byczycie, bzdurzycie, bzyczycie, cerezycie, chabazycie, chałturzycie, chandryczycie, charczycie, chmurzycie, chrzęszczycie, chytrzycie, cieszycie, ciszycie, ciurczycie, cudaczycie, cukrzycie, czapierzycie, czupurz [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string tetrzycie {
            get {
                return ResourceManager.GetString("tetrzycie", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ampli, apli, chrypli, ciepli, cierpli, cypli, czapli, Czapli, dociepli, dupli, dziupli, estopli, exempli, grępli, haspli, heksapli, hopli, karpli, karypli, knypli, kordupli, krępli, kropli, krzepli, kumpli, kupli, kurdupli, kwadrupli, multipli, nieciepli, nieczapli, nieochrypli, nieoklapli, nieokrzepli, nieoślepli, niepoślepli, niepółciepli, niepółoślepli, nieschrypli, nieskrzepli, nieszczupli, nieścierpli, niewpółciepli, niezachrypli, niezakrzepli, ochrypli, ociepli, oklapli, okrzepli, opli, oślepli, papli [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string trepli {
            get {
                return ResourceManager.GetString("trepli", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu abażurku, ażurku, biurku, burku, garniturku, Jurku, kangurku, kapturku, knurku, kocurku, kosturku, kurku, marmurku, mazurku, Misiurku, młodoturku, mundurku, murku, mysiurku, nurku, obszczymurku, okurku, pazurku, płetwonurku, podkurku, przymurku, siurku, szczurku, szambonurku, sznurku, Szurku, tamburku, tellurku, tużurku, wilczurku, żurku, robotny fiucie.
        /// </summary>
        internal static string turq {
            get {
                return ResourceManager.GetString("turq", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu witam na kanale i życzę miłej zabawy, cześć, kopę lat, siemanko witam na moim kanale, witam witam również, no elo, salam alejkum, привет, dzińdybry, siemaszki, gitara siema, dobrý den.
        /// </summary>
        internal static string witam {
            get {
                return ResourceManager.GetString("witam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kurw,chuj,pierdol,pierdal,jeb,cyka,blyat.
        /// </summary>
        internal static string wulg {
            get {
                return ResourceManager.GetString("wulg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu może byś tak kurwa nie przeklinał, co?, bez wulgaryzmów proszę, na ten kanał zaglądają dzieci, ostrożniej z językiem, to kanał PG13, czy mam ci język uciąć?, przestań przeklinać pedale bo cię stąd wypierdolę dyscyplinarnie, pambuk płacze jak przeklinasz, mów do mnie brzydko, Kath bączy jak przeklinasz, proszę tu nie przeklinać to porządna knajpa, nie ma takiego przeklinania chuju, блять)))))))))).
        /// </summary>
        internal static string wulg_response {
            get {
                return ResourceManager.GetString("wulg_response", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Agnisiu, Barcisiu, czarownisiu, delikatnisiu, dowcipnisiu, Fabisiu, fisiu, grzecznisiu, gumisiu, Jadwisiu, Klisiu, konisiu, Kubisiu, Kulisiu, Ludwisiu, misiu, modnisiu, Monisiu, nabożnisiu, nadobnisiu, ostrożnisiu, pięknisiu, pobożnisiu, porządnisiu, publisiu, skromnisiu, Skubisiu, strojnisiu, subtelnisiu, tantnisiu, teletubisiu, trefnisiu, układnisiu, wybrednisiu, wygodnisiu, wykwintnisiu, wytwornisiu, zakulisiu, zalotnisiu, Zdzisiu, żartownisiu, Brysiu, bysiu, chłoptysiu, chłopysiu, forysiu, Gabrysiu, Gaw [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string xysiu {
            get {
                return ResourceManager.GetString("xysiu", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu długoryjec, Dunajec, Gorajec, Grojec, Grójec, jajec, kitajec, kojec, Kondrajec, Koszajec, liszajec, mołojec, nohajec, Ochojec, ogrojec, ogrójec, Podhajec, Przychojec, ryjec, skojec, Strojec, szkojec, tęgoryjec, Wiejec, Wujec, wyjec, Zarajec, zbrojec, Złojec, srojec, cyklotron.
        /// </summary>
        internal static string yojec {
            get {
                return ResourceManager.GetString("yojec", resourceCulture);
            }
        }
    }
}
